import os
import time
import numpy as np

def profile_tflite_model(tflite_path, input_shape, is_quantized=False):
    """
    Profiles a TFLite model using the standard tf.lite.Interpreter.
    Measures Model Size, estimated RAM footprint, and inference Latency.
    """
    if not os.path.exists(tflite_path):
        return None
        
    try:
        import tensorflow as tf
    except ImportError:
        print("TensorFlow not found. Please install to profile models.")
        return None
        
    # 1. Model Size (Flash / ROM)
    size_kb = os.path.getsize(tflite_path) / 1024.0
    
    # Initialize Interpreter
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()
    
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # 2. Estimated RAM Footprint
    # For TinyML, RAM is often the strict bottleneck (e.g. < 256KB total SRAM).
    # We estimate the runtime arena size by summing up all intermediate tensors.
    tensor_details = interpreter.get_tensor_details()
    
    total_arena_ram_kb = 0.0
    for t in tensor_details:
        shape = t['shape']
        if shape.size > 0:
            num_elements = np.prod(shape)
            # 1 byte for int8/uint8, 4 bytes for float32/int32
            dtype_size = 1 if t['dtype'] in [np.int8, np.uint8] else 4
            total_arena_ram_kb += (num_elements * dtype_size)
    total_arena_ram_kb /= 1024.0

    # 3. Latency
    input_index = input_details[0]['index']
    output_index = output_details[0]['index']
    
    # Generate random input representing the sensors
    if is_quantized:
        scale, zero_point = input_details[0]['quantization']
        dummy_input = np.random.randn(1, *input_shape)
        if scale > 0: # Ensure valid quantization parameters exist
            dummy_input = (dummy_input / scale) + zero_point
        dummy_input = np.clip(dummy_input, -128, 127).astype(np.int8)
    else:
        dummy_input = np.random.randn(1, *input_shape).astype(np.float32)
        
    # Warmup
    interpreter.set_tensor(input_index, dummy_input)
    interpreter.invoke()
    
    # Measure Latency (average over 100 iterations)
    num_runs = 100
    start_time = time.time()
    for _ in range(num_runs):
        interpreter.set_tensor(input_index, dummy_input)
        interpreter.invoke()
        _ = interpreter.get_tensor(output_index)
    end_time = time.time()
    
    avg_latency_ms = ((end_time - start_time) / num_runs) * 1000.0
    
    return {
        "size_kb": size_kb,
        "ram_kb": total_arena_ram_kb,
        "latency_ms": avg_latency_ms
    }

def print_paper_summary(results_dict):
    """
    Prints a formatted table suitable for academic paper reporting.
    
    Paper Interpretation Notes:
    - Model Size (Flash): Dictates if it can fit in program memory. (e.g. Cortex-M4 has ~512KB).
    - Est. RAM (SRAM): The peak memory needed during execution. (e.g. Cortex-M4 has ~128KB).
    - Latency: Usually scales linearly with clock speed on target MCU. The profile here gives 
      relative hardware-independent differences (assuming you profile on the same host CPU).
    - Float vs INT8: You want to demonstrate in the paper that INT8 achieves ~4x reduction in 
      size/RAM while preserving validation MSE.
    """
    print("\n" + "="*80)
    print(" PAPER REPORT: TINYML HARDWARE PROFILING SUMMARY")
    print("="*80)
    print(f"{'Model Profile':<25} | {'Size Flash (KB)':<17} | {'Est. RAM (KB)':<15} | {'Latency (ms)':<15}")
    print("-" * 80)
    
    for model_name, metrics in results_dict.items():
        if metrics:
            print(f"{model_name:<25} | {metrics['size_kb']:<17.2f} | {metrics['ram_kb']:<15.2f} | {metrics['latency_ms']:<15.2f}")
    print("=" * 80)
    print("* Note: Latency measured on Host CPU; scale down relative to target MCU clock speed (e.g., 64MHz).\n")


if __name__ == "__main__":
    print("="*60)
    print(" TINYML PROFILING INSTRUCTIONS FOR GOOGLE COLAB")
    print("="*60)
    print("Make sure you have exported your models via tinyml_export.py first.")
    print("\nRunning example profiling...")
    
    WINDOW_SIZE = 12
    NUM_FEATURES = 8
    
    export_dir = "export_models"
    
    # Models to profile (generated by tinyml_export.py)
    models_to_test = {
        "TinyMLP (Float32)": (os.path.join(export_dir, "tinymlp_float.tflite"), False),
        "TinyMLP (INT8 Quant)": (os.path.join(export_dir, "tinymlp_quant_int8.tflite"), True),
        "TinyCNN1D (Float32)": (os.path.join(export_dir, "tinycnn1d_float.tflite"), False),
        "TinyCNN1D (INT8 Quant)": (os.path.join(export_dir, "tinycnn1d_quant_int8.tflite"), True),
    }
    
    results = {}
    for name, (path, is_quant) in models_to_test.items():
        if os.path.exists(path):
            results[name] = profile_tflite_model(path, (WINDOW_SIZE, NUM_FEATURES), is_quantized=is_quant)
        else:
            print(f"Skipping {name}: File {path} not found.")
            
    if results:
        print_paper_summary(results)
    else:
        print("No models found. Run tinyml_export.py first to generate the TFLite payloads.")
